threshold: 48.4
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - Mercy::Report#json
      - Mercy::Report#initialize
  ReturnTag:
    enabled: true
    exclude:
      - Mercy::PeriodParser#period
      - Mercy::Report#json
  Summary::Presence:
    enabled: true
    exclude:
      - Mercy::PeriodParser#initialize
      - Mercy::PeriodParser#period
      - Mercy::Report#initialize
      - Mercy::Report#json
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
